### ISSUE TITLE
Test coverage

### ISSUE THREAD

**Issue by ccakes** [megaport/Java-MegaportAPI#1]
Given this is external facing and a fresh chunk of code, we need to make sure test coverage on this is *high*

The words "test-driven development" make me shudder a bit, but I think we should define an API for the objects, write some tests and then build to that. At some point, say a 1.0-RC type milestone we finalise the test schema and then no more changes to those. Then in theory, if code changes alter the input/output values from the library we break.

Thoughts? Unless anyone has any serious objections to this, I think it's pretty important.

**Comment by adampwells** [comment]
I had in mind using the tests here to validate the stability of the API, in addition to Selenium.

I would suggest running the tests here prior to an API release etc.
