### ISSUE TITLE
exception in handleError

### ISSUE THREAD

**Issue by dannyM42** [megaport/Java-MegaportAPI#2]
I try to create a MegaPort similar to the test examples:
```java
MegaportServiceDto ms = new MegaportServiceDto();
ms.setLocationId(locationId);  // determined above
ms.setProductType(ProductType.MEGAPORT);
ms.setTerm(1);
ms.setProductName("My Test Port");
ms.setPortSpeed(1000);
ms.setProvisioningStatus(ProvisioningStatus.DESIGN);
List<MegaportServiceDto> msl = new ArrayList<>();
msl.add(ms);
List<ServiceLineItemDto> sli = session.validateOrder(msl);
```

This fails - probably due to my unfinished account. However, I don't see the actual reason for failing, which is the actual problem described here. In fact, handleError throws an unexpected exception reporting some internal problem:
```
java.lang.ClassCastException: java.util.ArrayList cannot be cast to java.lang.String
        at com.megaport.api.client.MegaportApiSession.handleError(MegaportApiSession.java:884)
        at com.megaport.api.client.MegaportApiSession.validateOrder(MegaportApiSession.java:353)
```

**Comment by adampwells** [comment]
We'll check this out probably today, and try to get a new version out in the next few days.

**Comment by adampwells** [comment]
Hi @dannyM42 - I can't reproduce this issue with a 'bad' location (eg -3), or with some good locations... to track this down, I will need to know the location Id that gives you this error.

**Comment by dannyM42** [comment]
Location is my case is 66, i.e. "Equinix SV1".

The errorResponseMap is actually not a HashMap<String,String> but a HashMap<String,Object> since in my example it contains the following:
"markets" : java.util.ArrayList
"error" : java.lang.String
The "markets" list contains "MEGAPORT_US", and the error is "Missing markets: USA".

However, even when adding ms.setMarket("USA") or ms.setMarket("MEGAPORT_US") it does not work. And looking at PortOrdersTest.java it should work without setting the market.

So, first problem is that handleError() fails if there is something different than a String value in the errorResponseMap, which can actually happen.
Concerning the missing market I'll write to the support address and provide further details.

**Comment by adampwells** [comment]
OK, so the problem is that your account does not have a billing market set up for the USA.  In https://megaport.al you need to go to Company -> Billing Markets and set up the USA market.  By setting up the billing market, you are agreeing to T&Cs, and providing information about who gets the invoice etc etc.

The API is correctly returning a 400 in this case, but the SDK is choking on the response; I guess we never tested that scenario...  I'll confirm what is going on handling that response, and get another version out in the next few days.
